package com.css.cloud.quartz.zhjc.jsq.dao;

import com.css.cloud.quartz.zhjc.jsq.entity.TMatterStatistics;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Map;

public interface TMatterStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTER_STATISTICS
     *
     * @mbggenerated
     */
    int insert(TMatterStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTER_STATISTICS
     *
     * @mbggenerated
     */
    int insertSelective(TMatterStatistics record);

    // 认领事项统计
    Map<String,BigDecimal> countRecieveMatter(@Param("monday") String monday, @Param("nextMonday") String nextday);
}