package com.css.cloud.quartz.zhjc.yxq.dao;

import com.css.cloud.quartz.zhjc.yxq.entity.TZhjcYxBmdf;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TZhjcYxBmdfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    int insert(TZhjcYxBmdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    int insertSelective(TZhjcYxBmdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    TZhjcYxBmdf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TZhjcYxBmdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_BMDF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TZhjcYxBmdf record);

    List<Map<String,Object>> getBmdfData(@Param("year")String year,@Param("month")String month);
}