package com.css.cloud.quartz.zhjc.yxq.dao;

import com.css.cloud.quartz.zhjc.yxq.entity.TZhjcYxMybj;

import java.util.Map;

public interface TZhjcYxMybjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    int insert(TZhjcYxMybj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    int insertSelective(TZhjcYxMybj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    TZhjcYxMybj selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TZhjcYxMybj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_MYBJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TZhjcYxMybj record);

    //统计办件时间
    Map getBjsjData(String month);

    //统计办件综合走势
    Map getBjzhzsData(String month);
}