package com.css.cloud.quartz.zhjc.yxq.dao;

import com.css.cloud.quartz.zhjc.yxq.entity.TZhjcYxSxrz;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface TZhjcYxSxrzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_SXRZ
     *
     * @mbggenerated
     */
    int insert(TZhjcYxSxrz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_SXRZ
     *
     * @mbggenerated
     */
    int insertSelective(TZhjcYxSxrz record);

    //事项入驻
    List<Map<String,BigDecimal>> getSxrzData();

}