package com.css.cloud.quartz.zhjc.yxq.dao;

import com.css.cloud.quartz.zhjc.yxq.entity.TZhjcYxWbsd;

import java.util.Map;

public interface TZhjcYxWbsdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    int insert(TZhjcYxWbsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    int insertSelective(TZhjcYxWbsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    TZhjcYxWbsd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TZhjcYxWbsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZHJC_YX_WBSD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TZhjcYxWbsd record);

    //网办深度统计
    Map getWbsdData();
}