package com.css.cloud.quartz.zhjc.jsq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TMatterStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.MS_AREACODE
     *
     * @mbggenerated
     */
    private String msAreacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.MS_ORGCODE
     *
     * @mbggenerated
     */
    private String msOrgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.MS_TYPE
     *
     * @mbggenerated
     */
    private String msType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.SHOULD_NUM
     *
     * @mbggenerated
     */
    private BigDecimal shouldNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.DONE_NUM
     *
     * @mbggenerated
     */
    private BigDecimal doneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.MS_DATE
     *
     * @mbggenerated
     */
    private Date msDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MATTER_STATISTICS.MS_NAME
     *
     * @mbggenerated
     */
    private String msName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.ID
     *
     * @return the value of MATTER_STATISTICS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.ID
     *
     * @param id the value for MATTER_STATISTICS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.MS_AREACODE
     *
     * @return the value of MATTER_STATISTICS.MS_AREACODE
     *
     * @mbggenerated
     */
    public String getMsAreacode() {
        return msAreacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.MS_AREACODE
     *
     * @param msAreacode the value for MATTER_STATISTICS.MS_AREACODE
     *
     * @mbggenerated
     */
    public void setMsAreacode(String msAreacode) {
        this.msAreacode = msAreacode == null ? null : msAreacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.MS_ORGCODE
     *
     * @return the value of MATTER_STATISTICS.MS_ORGCODE
     *
     * @mbggenerated
     */
    public String getMsOrgcode() {
        return msOrgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.MS_ORGCODE
     *
     * @param msOrgcode the value for MATTER_STATISTICS.MS_ORGCODE
     *
     * @mbggenerated
     */
    public void setMsOrgcode(String msOrgcode) {
        this.msOrgcode = msOrgcode == null ? null : msOrgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.MS_TYPE
     *
     * @return the value of MATTER_STATISTICS.MS_TYPE
     *
     * @mbggenerated
     */
    public String getMsType() {
        return msType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.MS_TYPE
     *
     * @param msType the value for MATTER_STATISTICS.MS_TYPE
     *
     * @mbggenerated
     */
    public void setMsType(String msType) {
        this.msType = msType == null ? null : msType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.SHOULD_NUM
     *
     * @return the value of MATTER_STATISTICS.SHOULD_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getShouldNum() {
        return shouldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.SHOULD_NUM
     *
     * @param shouldNum the value for MATTER_STATISTICS.SHOULD_NUM
     *
     * @mbggenerated
     */
    public void setShouldNum(BigDecimal shouldNum) {
        this.shouldNum = shouldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.DONE_NUM
     *
     * @return the value of MATTER_STATISTICS.DONE_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getDoneNum() {
        return doneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.DONE_NUM
     *
     * @param doneNum the value for MATTER_STATISTICS.DONE_NUM
     *
     * @mbggenerated
     */
    public void setDoneNum(BigDecimal doneNum) {
        this.doneNum = doneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.MS_DATE
     *
     * @return the value of MATTER_STATISTICS.MS_DATE
     *
     * @mbggenerated
     */
    public Date getMsDate() {
        return msDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.MS_DATE
     *
     * @param msDate the value for MATTER_STATISTICS.MS_DATE
     *
     * @mbggenerated
     */
    public void setMsDate(Date msDate) {
        this.msDate = msDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MATTER_STATISTICS.MS_NAME
     *
     * @return the value of MATTER_STATISTICS.MS_NAME
     *
     * @mbggenerated
     */
    public String getMsName() {
        return msName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MATTER_STATISTICS.MS_NAME
     *
     * @param msName the value for MATTER_STATISTICS.MS_NAME
     *
     * @mbggenerated
     */
    public void setMsName(String msName) {
        this.msName = msName == null ? null : msName.trim();
    }
}