package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxRdsx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.SXBM
     *
     * @mbggenerated
     */
    private String sxbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.SXMC
     *
     * @mbggenerated
     */
    private String sxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.SXBJS
     *
     * @mbggenerated
     */
    private Short sxbjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_RDSX.TJYF
     *
     * @mbggenerated
     */
    private Date tjyf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.ID
     *
     * @return the value of T_ZHJC_YX_RDSX.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.ID
     *
     * @param id the value for T_ZHJC_YX_RDSX.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.SXBM
     *
     * @return the value of T_ZHJC_YX_RDSX.SXBM
     *
     * @mbggenerated
     */
    public String getSxbm() {
        return sxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.SXBM
     *
     * @param sxbm the value for T_ZHJC_YX_RDSX.SXBM
     *
     * @mbggenerated
     */
    public void setSxbm(String sxbm) {
        this.sxbm = sxbm == null ? null : sxbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.SXMC
     *
     * @return the value of T_ZHJC_YX_RDSX.SXMC
     *
     * @mbggenerated
     */
    public String getSxmc() {
        return sxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.SXMC
     *
     * @param sxmc the value for T_ZHJC_YX_RDSX.SXMC
     *
     * @mbggenerated
     */
    public void setSxmc(String sxmc) {
        this.sxmc = sxmc == null ? null : sxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.SXBJS
     *
     * @return the value of T_ZHJC_YX_RDSX.SXBJS
     *
     * @mbggenerated
     */
    public Short getSxbjs() {
        return sxbjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.SXBJS
     *
     * @param sxbjs the value for T_ZHJC_YX_RDSX.SXBJS
     *
     * @mbggenerated
     */
    public void setSxbjs(Short sxbjs) {
        this.sxbjs = sxbjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.QHBM
     *
     * @return the value of T_ZHJC_YX_RDSX.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_RDSX.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.QHMC
     *
     * @return the value of T_ZHJC_YX_RDSX.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_RDSX.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.BMBM
     *
     * @return the value of T_ZHJC_YX_RDSX.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_RDSX.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.BMMC
     *
     * @return the value of T_ZHJC_YX_RDSX.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_RDSX.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.GXSJ
     *
     * @return the value of T_ZHJC_YX_RDSX.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_RDSX.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_RDSX.TJYF
     *
     * @return the value of T_ZHJC_YX_RDSX.TJYF
     *
     * @mbggenerated
     */
    public Date getTjyf() {
        return tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_RDSX.TJYF
     *
     * @param tjyf the value for T_ZHJC_YX_RDSX.TJYF
     *
     * @mbggenerated
     */
    public void setTjyf(Date tjyf) {
        this.tjyf = tjyf;
    }
}