package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxBjtj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.BJJL
     *
     * @mbggenerated
     */
    private Short bjjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.SLJL
     *
     * @mbggenerated
     */
    private Short sljl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.WSYSL
     *
     * @mbggenerated
     */
    private Short wsysl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.WSSSL
     *
     * @mbggenerated
     */
    private Short wsssl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.WSBJL
     *
     * @mbggenerated
     */
    private Short wsbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.XXSLL
     *
     * @mbggenerated
     */
    private Short xxsll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.XXZBL
     *
     * @mbggenerated
     */
    private Short xxzbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.XXBJL
     *
     * @mbggenerated
     */
    private Short xxbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.QHDM
     *
     * @mbggenerated
     */
    private String qhdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BJTJ.TJSJ
     *
     * @mbggenerated
     */
    private Date tjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.ID
     *
     * @return the value of T_ZHJC_YX_BJTJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.ID
     *
     * @param id the value for T_ZHJC_YX_BJTJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.BJJL
     *
     * @return the value of T_ZHJC_YX_BJTJ.BJJL
     *
     * @mbggenerated
     */
    public Short getBjjl() {
        return bjjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.BJJL
     *
     * @param bjjl the value for T_ZHJC_YX_BJTJ.BJJL
     *
     * @mbggenerated
     */
    public void setBjjl(Short bjjl) {
        this.bjjl = bjjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.SLJL
     *
     * @return the value of T_ZHJC_YX_BJTJ.SLJL
     *
     * @mbggenerated
     */
    public Short getSljl() {
        return sljl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.SLJL
     *
     * @param sljl the value for T_ZHJC_YX_BJTJ.SLJL
     *
     * @mbggenerated
     */
    public void setSljl(Short sljl) {
        this.sljl = sljl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.WSYSL
     *
     * @return the value of T_ZHJC_YX_BJTJ.WSYSL
     *
     * @mbggenerated
     */
    public Short getWsysl() {
        return wsysl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.WSYSL
     *
     * @param wsysl the value for T_ZHJC_YX_BJTJ.WSYSL
     *
     * @mbggenerated
     */
    public void setWsysl(Short wsysl) {
        this.wsysl = wsysl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.WSSSL
     *
     * @return the value of T_ZHJC_YX_BJTJ.WSSSL
     *
     * @mbggenerated
     */
    public Short getWsssl() {
        return wsssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.WSSSL
     *
     * @param wsssl the value for T_ZHJC_YX_BJTJ.WSSSL
     *
     * @mbggenerated
     */
    public void setWsssl(Short wsssl) {
        this.wsssl = wsssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.WSBJL
     *
     * @return the value of T_ZHJC_YX_BJTJ.WSBJL
     *
     * @mbggenerated
     */
    public Short getWsbjl() {
        return wsbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.WSBJL
     *
     * @param wsbjl the value for T_ZHJC_YX_BJTJ.WSBJL
     *
     * @mbggenerated
     */
    public void setWsbjl(Short wsbjl) {
        this.wsbjl = wsbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.XXSLL
     *
     * @return the value of T_ZHJC_YX_BJTJ.XXSLL
     *
     * @mbggenerated
     */
    public Short getXxsll() {
        return xxsll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.XXSLL
     *
     * @param xxsll the value for T_ZHJC_YX_BJTJ.XXSLL
     *
     * @mbggenerated
     */
    public void setXxsll(Short xxsll) {
        this.xxsll = xxsll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.XXZBL
     *
     * @return the value of T_ZHJC_YX_BJTJ.XXZBL
     *
     * @mbggenerated
     */
    public Short getXxzbl() {
        return xxzbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.XXZBL
     *
     * @param xxzbl the value for T_ZHJC_YX_BJTJ.XXZBL
     *
     * @mbggenerated
     */
    public void setXxzbl(Short xxzbl) {
        this.xxzbl = xxzbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.XXBJL
     *
     * @return the value of T_ZHJC_YX_BJTJ.XXBJL
     *
     * @mbggenerated
     */
    public Short getXxbjl() {
        return xxbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.XXBJL
     *
     * @param xxbjl the value for T_ZHJC_YX_BJTJ.XXBJL
     *
     * @mbggenerated
     */
    public void setXxbjl(Short xxbjl) {
        this.xxbjl = xxbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.QHDM
     *
     * @return the value of T_ZHJC_YX_BJTJ.QHDM
     *
     * @mbggenerated
     */
    public String getQhdm() {
        return qhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.QHDM
     *
     * @param qhdm the value for T_ZHJC_YX_BJTJ.QHDM
     *
     * @mbggenerated
     */
    public void setQhdm(String qhdm) {
        this.qhdm = qhdm == null ? null : qhdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.QHMC
     *
     * @return the value of T_ZHJC_YX_BJTJ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_BJTJ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.BMBM
     *
     * @return the value of T_ZHJC_YX_BJTJ.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_BJTJ.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.BMMC
     *
     * @return the value of T_ZHJC_YX_BJTJ.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_BJTJ.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.GXSJ
     *
     * @return the value of T_ZHJC_YX_BJTJ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_BJTJ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BJTJ.TJSJ
     *
     * @return the value of T_ZHJC_YX_BJTJ.TJSJ
     *
     * @mbggenerated
     */
    public Date getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BJTJ.TJSJ
     *
     * @param tjsj the value for T_ZHJC_YX_BJTJ.TJSJ
     *
     * @mbggenerated
     */
    public void setTjsj(Date tjsj) {
        this.tjsj = tjsj;
    }
}