package com.css.cloud.quartz.zhjc.yxq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TZhjcYxSxrz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.ZSXS
     *
     * @mbggenerated
     */
    private BigDecimal zsxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.TYSPRZS
     *
     * @mbggenerated
     */
    private BigDecimal tysprzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.ZJXTRZ
     *
     * @mbggenerated
     */
    private BigDecimal zjxtrz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.SJXTRZ
     *
     * @mbggenerated
     */
    private BigDecimal sjxtrz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.TYSPLT
     *
     * @mbggenerated
     */
    private BigDecimal tysplt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.ZJXTLT
     *
     * @mbggenerated
     */
    private BigDecimal zjxtlt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.SJXTLT
     *
     * @mbggenerated
     */
    private BigDecimal sjxtlt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_SXRZ.TJSJ
     *
     * @mbggenerated
     */
    private Date tjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.ID
     *
     * @return the value of T_ZHJC_YX_SXRZ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.ID
     *
     * @param id the value for T_ZHJC_YX_SXRZ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.ZSXS
     *
     * @return the value of T_ZHJC_YX_SXRZ.ZSXS
     *
     * @mbggenerated
     */
    public BigDecimal getZsxs() {
        return zsxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.ZSXS
     *
     * @param zsxs the value for T_ZHJC_YX_SXRZ.ZSXS
     *
     * @mbggenerated
     */
    public void setZsxs(BigDecimal zsxs) {
        this.zsxs = zsxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.TYSPRZS
     *
     * @return the value of T_ZHJC_YX_SXRZ.TYSPRZS
     *
     * @mbggenerated
     */
    public BigDecimal getTysprzs() {
        return tysprzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.TYSPRZS
     *
     * @param tysprzs the value for T_ZHJC_YX_SXRZ.TYSPRZS
     *
     * @mbggenerated
     */
    public void setTysprzs(BigDecimal tysprzs) {
        this.tysprzs = tysprzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.ZJXTRZ
     *
     * @return the value of T_ZHJC_YX_SXRZ.ZJXTRZ
     *
     * @mbggenerated
     */
    public BigDecimal getZjxtrz() {
        return zjxtrz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.ZJXTRZ
     *
     * @param zjxtrz the value for T_ZHJC_YX_SXRZ.ZJXTRZ
     *
     * @mbggenerated
     */
    public void setZjxtrz(BigDecimal zjxtrz) {
        this.zjxtrz = zjxtrz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.SJXTRZ
     *
     * @return the value of T_ZHJC_YX_SXRZ.SJXTRZ
     *
     * @mbggenerated
     */
    public BigDecimal getSjxtrz() {
        return sjxtrz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.SJXTRZ
     *
     * @param sjxtrz the value for T_ZHJC_YX_SXRZ.SJXTRZ
     *
     * @mbggenerated
     */
    public void setSjxtrz(BigDecimal sjxtrz) {
        this.sjxtrz = sjxtrz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.TYSPLT
     *
     * @return the value of T_ZHJC_YX_SXRZ.TYSPLT
     *
     * @mbggenerated
     */
    public BigDecimal getTysplt() {
        return tysplt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.TYSPLT
     *
     * @param tysplt the value for T_ZHJC_YX_SXRZ.TYSPLT
     *
     * @mbggenerated
     */
    public void setTysplt(BigDecimal tysplt) {
        this.tysplt = tysplt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.ZJXTLT
     *
     * @return the value of T_ZHJC_YX_SXRZ.ZJXTLT
     *
     * @mbggenerated
     */
    public BigDecimal getZjxtlt() {
        return zjxtlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.ZJXTLT
     *
     * @param zjxtlt the value for T_ZHJC_YX_SXRZ.ZJXTLT
     *
     * @mbggenerated
     */
    public void setZjxtlt(BigDecimal zjxtlt) {
        this.zjxtlt = zjxtlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.SJXTLT
     *
     * @return the value of T_ZHJC_YX_SXRZ.SJXTLT
     *
     * @mbggenerated
     */
    public BigDecimal getSjxtlt() {
        return sjxtlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.SJXTLT
     *
     * @param sjxtlt the value for T_ZHJC_YX_SXRZ.SJXTLT
     *
     * @mbggenerated
     */
    public void setSjxtlt(BigDecimal sjxtlt) {
        this.sjxtlt = sjxtlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.QHBM
     *
     * @return the value of T_ZHJC_YX_SXRZ.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_SXRZ.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.QHMC
     *
     * @return the value of T_ZHJC_YX_SXRZ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_SXRZ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.BMBM
     *
     * @return the value of T_ZHJC_YX_SXRZ.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_SXRZ.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.BMMC
     *
     * @return the value of T_ZHJC_YX_SXRZ.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_SXRZ.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.GXSJ
     *
     * @return the value of T_ZHJC_YX_SXRZ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_SXRZ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_SXRZ.TJSJ
     *
     * @return the value of T_ZHJC_YX_SXRZ.TJSJ
     *
     * @mbggenerated
     */
    public Date getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_SXRZ.TJSJ
     *
     * @param tjsj the value for T_ZHJC_YX_SXRZ.TJSJ
     *
     * @mbggenerated
     */
    public void setTjsj(Date tjsj) {
        this.tjsj = tjsj;
    }
}