package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxHhp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.HPS
     *
     * @mbggenerated
     */
    private Short hps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.HPYJS
     *
     * @mbggenerated
     */
    private Short hpyjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_HHP.TJSJ
     *
     * @mbggenerated
     */
    private Date tjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.ID
     *
     * @return the value of T_ZHJC_YX_HHP.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.ID
     *
     * @param id the value for T_ZHJC_YX_HHP.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.HPS
     *
     * @return the value of T_ZHJC_YX_HHP.HPS
     *
     * @mbggenerated
     */
    public Short getHps() {
        return hps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.HPS
     *
     * @param hps the value for T_ZHJC_YX_HHP.HPS
     *
     * @mbggenerated
     */
    public void setHps(Short hps) {
        this.hps = hps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.HPYJS
     *
     * @return the value of T_ZHJC_YX_HHP.HPYJS
     *
     * @mbggenerated
     */
    public Short getHpyjs() {
        return hpyjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.HPYJS
     *
     * @param hpyjs the value for T_ZHJC_YX_HHP.HPYJS
     *
     * @mbggenerated
     */
    public void setHpyjs(Short hpyjs) {
        this.hpyjs = hpyjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.BMBM
     *
     * @return the value of T_ZHJC_YX_HHP.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_HHP.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.BMMC
     *
     * @return the value of T_ZHJC_YX_HHP.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_HHP.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.QHBM
     *
     * @return the value of T_ZHJC_YX_HHP.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_HHP.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.QHMC
     *
     * @return the value of T_ZHJC_YX_HHP.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_HHP.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.GXSJ
     *
     * @return the value of T_ZHJC_YX_HHP.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_HHP.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_HHP.TJSJ
     *
     * @return the value of T_ZHJC_YX_HHP.TJSJ
     *
     * @mbggenerated
     */
    public Date getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_HHP.TJSJ
     *
     * @param tjsj the value for T_ZHJC_YX_HHP.TJSJ
     *
     * @mbggenerated
     */
    public void setTjsj(Date tjsj) {
        this.tjsj = tjsj;
    }
}