package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxMypdtj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.PJQHSJ
     *
     * @mbggenerated
     */
    private Double pjqhsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.PJJHSJ
     *
     * @mbggenerated
     */
    private Double pjjhsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.ZJHSL
     *
     * @mbggenerated
     */
    private Short zjhsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.TJYF
     *
     * @mbggenerated
     */
    private Date tjyf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYPDTJ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.ID
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.ID
     *
     * @param id the value for T_ZHJC_YX_MYPDTJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.PJQHSJ
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.PJQHSJ
     *
     * @mbggenerated
     */
    public Double getPjqhsj() {
        return pjqhsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.PJQHSJ
     *
     * @param pjqhsj the value for T_ZHJC_YX_MYPDTJ.PJQHSJ
     *
     * @mbggenerated
     */
    public void setPjqhsj(Double pjqhsj) {
        this.pjqhsj = pjqhsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.PJJHSJ
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.PJJHSJ
     *
     * @mbggenerated
     */
    public Double getPjjhsj() {
        return pjjhsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.PJJHSJ
     *
     * @param pjjhsj the value for T_ZHJC_YX_MYPDTJ.PJJHSJ
     *
     * @mbggenerated
     */
    public void setPjjhsj(Double pjjhsj) {
        this.pjjhsj = pjjhsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.ZJHSL
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.ZJHSL
     *
     * @mbggenerated
     */
    public Short getZjhsl() {
        return zjhsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.ZJHSL
     *
     * @param zjhsl the value for T_ZHJC_YX_MYPDTJ.ZJHSL
     *
     * @mbggenerated
     */
    public void setZjhsl(Short zjhsl) {
        this.zjhsl = zjhsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.TJYF
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.TJYF
     *
     * @mbggenerated
     */
    public Date getTjyf() {
        return tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.TJYF
     *
     * @param tjyf the value for T_ZHJC_YX_MYPDTJ.TJYF
     *
     * @mbggenerated
     */
    public void setTjyf(Date tjyf) {
        this.tjyf = tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.BMBM
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_MYPDTJ.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.BMMC
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_MYPDTJ.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.QHBM
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_MYPDTJ.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.QHMC
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_MYPDTJ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYPDTJ.GXSJ
     *
     * @return the value of T_ZHJC_YX_MYPDTJ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYPDTJ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_MYPDTJ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }
}