package com.css.cloud.quartz.zhjc.yxq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TZhjcYxBmdf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.BQDF
     *
     * @mbggenerated
     */
    private Short bqdf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.BQPM
     *
     * @mbggenerated
     */
    private BigDecimal bqpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.SQDF
     *
     * @mbggenerated
     */
    private Short sqdf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.SQPM
     *
     * @mbggenerated
     */
    private BigDecimal sqpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.PMBHZ
     *
     * @mbggenerated
     */
    private BigDecimal PMBHZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.TJNF
     *
     * @mbggenerated
     */
    private String tjnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.TJYF
     *
     * @mbggenerated
     */
    private String tjyf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_BMDF.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.ID
     *
     * @return the value of T_ZHJC_YX_BMDF.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.ID
     *
     * @param id the value for T_ZHJC_YX_BMDF.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.BMBM
     *
     * @return the value of T_ZHJC_YX_BMDF.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_BMDF.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.BMMC
     *
     * @return the value of T_ZHJC_YX_BMDF.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_BMDF.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.BQDF
     *
     * @return the value of T_ZHJC_YX_BMDF.BQDF
     *
     * @mbggenerated
     */
    public Short getBqdf() {
        return bqdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.BQDF
     *
     * @param bqdf the value for T_ZHJC_YX_BMDF.BQDF
     *
     * @mbggenerated
     */
    public void setBqdf(Short bqdf) {
        this.bqdf = bqdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.BQPM
     *
     * @return the value of T_ZHJC_YX_BMDF.BQPM
     *
     * @mbggenerated
     */
    public BigDecimal getBqpm() {
        return bqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.BQPM
     *
     * @param bqpm the value for T_ZHJC_YX_BMDF.BQPM
     *
     * @mbggenerated
     */
    public void setBqpm(BigDecimal bqpm) {
        this.bqpm = bqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.SQDF
     *
     * @return the value of T_ZHJC_YX_BMDF.SQDF
     *
     * @mbggenerated
     */
    public Short getSqdf() {
        return sqdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.SQDF
     *
     * @param sqdf the value for T_ZHJC_YX_BMDF.SQDF
     *
     * @mbggenerated
     */
    public void setSqdf(Short sqdf) {
        this.sqdf = sqdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.SQPM
     *
     * @return the value of T_ZHJC_YX_BMDF.SQPM
     *
     * @mbggenerated
     */
    public BigDecimal getSqpm() {
        return sqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.SQPM
     *
     * @param sqpm the value for T_ZHJC_YX_BMDF.SQPM
     *
     * @mbggenerated
     */
    public void setSqpm(BigDecimal sqpm) {
        this.sqpm = sqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.PMBHZ
     *
     * @return the value of T_ZHJC_YX_BMDF.PMBHZ
     *
     * @mbggenerated
     */
    public BigDecimal getPMBHZ() {
        return PMBHZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.PMBHZ
     *
     * @param PMBHZ the value for T_ZHJC_YX_BMDF.PMBHZ
     *
     * @mbggenerated
     */
    public void setPMBHZ(BigDecimal PMBHZ) {
        this.PMBHZ = PMBHZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.TJNF
     *
     * @return the value of T_ZHJC_YX_BMDF.TJNF
     *
     * @mbggenerated
     */
    public String getTjnf() {
        return tjnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.TJNF
     *
     * @param tjnf the value for T_ZHJC_YX_BMDF.TJNF
     *
     * @mbggenerated
     */
    public void setTjnf(String tjnf) {
        this.tjnf = tjnf == null ? null : tjnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.TJYF
     *
     * @return the value of T_ZHJC_YX_BMDF.TJYF
     *
     * @mbggenerated
     */
    public String getTjyf() {
        return tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.TJYF
     *
     * @param tjyf the value for T_ZHJC_YX_BMDF.TJYF
     *
     * @mbggenerated
     */
    public void setTjyf(String tjyf) {
        this.tjyf = tjyf == null ? null : tjyf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.QHBM
     *
     * @return the value of T_ZHJC_YX_BMDF.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_BMDF.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.QHMC
     *
     * @return the value of T_ZHJC_YX_BMDF.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_BMDF.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_BMDF.GXSJ
     *
     * @return the value of T_ZHJC_YX_BMDF.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_BMDF.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_BMDF.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }
}