package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxMybj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.PJSLSC
     *
     * @mbggenerated
     */
    private Short pjslsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.PJSPSC
     *
     * @mbggenerated
     */
    private Short pjspsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.PJBJSC
     *
     * @mbggenerated
     */
    private Short pjbjsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.PJFDSX
     *
     * @mbggenerated
     */
    private Short pjfdsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.PJBJSX
     *
     * @mbggenerated
     */
    private Short pjbjsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.TQBJL
     *
     * @mbggenerated
     */
    private Short tqbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.ZBJL
     *
     * @mbggenerated
     */
    private Short zbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.XSBJL
     *
     * @mbggenerated
     */
    private Short xsbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.XXBJL
     *
     * @mbggenerated
     */
    private Short xxbjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.TJYF
     *
     * @mbggenerated
     */
    private Date tjyf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_MYBJ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.ID
     *
     * @return the value of T_ZHJC_YX_MYBJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.ID
     *
     * @param id the value for T_ZHJC_YX_MYBJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.PJSLSC
     *
     * @return the value of T_ZHJC_YX_MYBJ.PJSLSC
     *
     * @mbggenerated
     */
    public Short getPjslsc() {
        return pjslsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.PJSLSC
     *
     * @param pjslsc the value for T_ZHJC_YX_MYBJ.PJSLSC
     *
     * @mbggenerated
     */
    public void setPjslsc(Short pjslsc) {
        this.pjslsc = pjslsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.PJSPSC
     *
     * @return the value of T_ZHJC_YX_MYBJ.PJSPSC
     *
     * @mbggenerated
     */
    public Short getPjspsc() {
        return pjspsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.PJSPSC
     *
     * @param pjspsc the value for T_ZHJC_YX_MYBJ.PJSPSC
     *
     * @mbggenerated
     */
    public void setPjspsc(Short pjspsc) {
        this.pjspsc = pjspsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.PJBJSC
     *
     * @return the value of T_ZHJC_YX_MYBJ.PJBJSC
     *
     * @mbggenerated
     */
    public Short getPjbjsc() {
        return pjbjsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.PJBJSC
     *
     * @param pjbjsc the value for T_ZHJC_YX_MYBJ.PJBJSC
     *
     * @mbggenerated
     */
    public void setPjbjsc(Short pjbjsc) {
        this.pjbjsc = pjbjsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.PJFDSX
     *
     * @return the value of T_ZHJC_YX_MYBJ.PJFDSX
     *
     * @mbggenerated
     */
    public Short getPjfdsx() {
        return pjfdsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.PJFDSX
     *
     * @param pjfdsx the value for T_ZHJC_YX_MYBJ.PJFDSX
     *
     * @mbggenerated
     */
    public void setPjfdsx(Short pjfdsx) {
        this.pjfdsx = pjfdsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.PJBJSX
     *
     * @return the value of T_ZHJC_YX_MYBJ.PJBJSX
     *
     * @mbggenerated
     */
    public Short getPjbjsx() {
        return pjbjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.PJBJSX
     *
     * @param pjbjsx the value for T_ZHJC_YX_MYBJ.PJBJSX
     *
     * @mbggenerated
     */
    public void setPjbjsx(Short pjbjsx) {
        this.pjbjsx = pjbjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.TQBJL
     *
     * @return the value of T_ZHJC_YX_MYBJ.TQBJL
     *
     * @mbggenerated
     */
    public Short getTqbjl() {
        return tqbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.TQBJL
     *
     * @param tqbjl the value for T_ZHJC_YX_MYBJ.TQBJL
     *
     * @mbggenerated
     */
    public void setTqbjl(Short tqbjl) {
        this.tqbjl = tqbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.ZBJL
     *
     * @return the value of T_ZHJC_YX_MYBJ.ZBJL
     *
     * @mbggenerated
     */
    public Short getZbjl() {
        return zbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.ZBJL
     *
     * @param zbjl the value for T_ZHJC_YX_MYBJ.ZBJL
     *
     * @mbggenerated
     */
    public void setZbjl(Short zbjl) {
        this.zbjl = zbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.XSBJL
     *
     * @return the value of T_ZHJC_YX_MYBJ.XSBJL
     *
     * @mbggenerated
     */
    public Short getXsbjl() {
        return xsbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.XSBJL
     *
     * @param xsbjl the value for T_ZHJC_YX_MYBJ.XSBJL
     *
     * @mbggenerated
     */
    public void setXsbjl(Short xsbjl) {
        this.xsbjl = xsbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.XXBJL
     *
     * @return the value of T_ZHJC_YX_MYBJ.XXBJL
     *
     * @mbggenerated
     */
    public Short getXxbjl() {
        return xxbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.XXBJL
     *
     * @param xxbjl the value for T_ZHJC_YX_MYBJ.XXBJL
     *
     * @mbggenerated
     */
    public void setXxbjl(Short xxbjl) {
        this.xxbjl = xxbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.QHBM
     *
     * @return the value of T_ZHJC_YX_MYBJ.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_MYBJ.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.QHMC
     *
     * @return the value of T_ZHJC_YX_MYBJ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_MYBJ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.BMBM
     *
     * @return the value of T_ZHJC_YX_MYBJ.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_MYBJ.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.BMMC
     *
     * @return the value of T_ZHJC_YX_MYBJ.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_MYBJ.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.TJYF
     *
     * @return the value of T_ZHJC_YX_MYBJ.TJYF
     *
     * @mbggenerated
     */
    public Date getTjyf() {
        return tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.TJYF
     *
     * @param tjyf the value for T_ZHJC_YX_MYBJ.TJYF
     *
     * @mbggenerated
     */
    public void setTjyf(Date tjyf) {
        this.tjyf = tjyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_MYBJ.GXSJ
     *
     * @return the value of T_ZHJC_YX_MYBJ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_MYBJ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_MYBJ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }
}