package com.css.cloud.quartz.zhjc.yxq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TZhjcYxZzsytj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.ZZBM
     *
     * @mbggenerated
     */
    private String zzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.ZZMC
     *
     * @mbggenerated
     */
    private String zzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.SQSYCS
     *
     * @mbggenerated
     */
    private Short sqsycs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.SQPM
     *
     * @mbggenerated
     */
    private BigDecimal sqpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.BQSYCS
     *
     * @mbggenerated
     */
    private Short bqsycs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.BQPM
     *
     * @mbggenerated
     */
    private BigDecimal bqpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.PMBH
     *
     * @mbggenerated
     */
    private BigDecimal pmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZSYTJ.TJRQ
     *
     * @mbggenerated
     */
    private Date tjrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.ID
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.ID
     *
     * @param id the value for T_ZHJC_YX_ZZSYTJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.ZZBM
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.ZZBM
     *
     * @mbggenerated
     */
    public String getZzbm() {
        return zzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.ZZBM
     *
     * @param zzbm the value for T_ZHJC_YX_ZZSYTJ.ZZBM
     *
     * @mbggenerated
     */
    public void setZzbm(String zzbm) {
        this.zzbm = zzbm == null ? null : zzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.ZZMC
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.ZZMC
     *
     * @mbggenerated
     */
    public String getZzmc() {
        return zzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.ZZMC
     *
     * @param zzmc the value for T_ZHJC_YX_ZZSYTJ.ZZMC
     *
     * @mbggenerated
     */
    public void setZzmc(String zzmc) {
        this.zzmc = zzmc == null ? null : zzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.SQSYCS
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.SQSYCS
     *
     * @mbggenerated
     */
    public Short getSqsycs() {
        return sqsycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.SQSYCS
     *
     * @param sqsycs the value for T_ZHJC_YX_ZZSYTJ.SQSYCS
     *
     * @mbggenerated
     */
    public void setSqsycs(Short sqsycs) {
        this.sqsycs = sqsycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.SQPM
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.SQPM
     *
     * @mbggenerated
     */
    public BigDecimal getSqpm() {
        return sqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.SQPM
     *
     * @param sqpm the value for T_ZHJC_YX_ZZSYTJ.SQPM
     *
     * @mbggenerated
     */
    public void setSqpm(BigDecimal sqpm) {
        this.sqpm = sqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.BQSYCS
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.BQSYCS
     *
     * @mbggenerated
     */
    public Short getBqsycs() {
        return bqsycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.BQSYCS
     *
     * @param bqsycs the value for T_ZHJC_YX_ZZSYTJ.BQSYCS
     *
     * @mbggenerated
     */
    public void setBqsycs(Short bqsycs) {
        this.bqsycs = bqsycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.BQPM
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.BQPM
     *
     * @mbggenerated
     */
    public BigDecimal getBqpm() {
        return bqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.BQPM
     *
     * @param bqpm the value for T_ZHJC_YX_ZZSYTJ.BQPM
     *
     * @mbggenerated
     */
    public void setBqpm(BigDecimal bqpm) {
        this.bqpm = bqpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.PMBH
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.PMBH
     *
     * @mbggenerated
     */
    public BigDecimal getPmbh() {
        return pmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.PMBH
     *
     * @param pmbh the value for T_ZHJC_YX_ZZSYTJ.PMBH
     *
     * @mbggenerated
     */
    public void setPmbh(BigDecimal pmbh) {
        this.pmbh = pmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.QHBM
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_ZZSYTJ.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.QHMC
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_ZZSYTJ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.GXSJ
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_ZZSYTJ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZSYTJ.TJRQ
     *
     * @return the value of T_ZHJC_YX_ZZSYTJ.TJRQ
     *
     * @mbggenerated
     */
    public Date getTjrq() {
        return tjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZSYTJ.TJRQ
     *
     * @param tjrq the value for T_ZHJC_YX_ZZSYTJ.TJRQ
     *
     * @mbggenerated
     */
    public void setTjrq(Date tjrq) {
        this.tjrq = tjrq;
    }
}