package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxZzlxtj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.ZZS
     *
     * @mbggenerated
     */
    private Short zzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.XZS
     *
     * @mbggenerated
     */
    private Short xzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.ZZLXBM
     *
     * @mbggenerated
     */
    private String zzlxbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.ZZLXMC
     *
     * @mbggenerated
     */
    private String zzlxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_ZZLXTJ.TJRQ
     *
     * @mbggenerated
     */
    private Date tjrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.ID
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.ID
     *
     * @param id the value for T_ZHJC_YX_ZZLXTJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.ZZS
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.ZZS
     *
     * @mbggenerated
     */
    public Short getZzs() {
        return zzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.ZZS
     *
     * @param zzs the value for T_ZHJC_YX_ZZLXTJ.ZZS
     *
     * @mbggenerated
     */
    public void setZzs(Short zzs) {
        this.zzs = zzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.XZS
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.XZS
     *
     * @mbggenerated
     */
    public Short getXzs() {
        return xzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.XZS
     *
     * @param xzs the value for T_ZHJC_YX_ZZLXTJ.XZS
     *
     * @mbggenerated
     */
    public void setXzs(Short xzs) {
        this.xzs = xzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.ZZLXBM
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.ZZLXBM
     *
     * @mbggenerated
     */
    public String getZzlxbm() {
        return zzlxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.ZZLXBM
     *
     * @param zzlxbm the value for T_ZHJC_YX_ZZLXTJ.ZZLXBM
     *
     * @mbggenerated
     */
    public void setZzlxbm(String zzlxbm) {
        this.zzlxbm = zzlxbm == null ? null : zzlxbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.ZZLXMC
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.ZZLXMC
     *
     * @mbggenerated
     */
    public String getZzlxmc() {
        return zzlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.ZZLXMC
     *
     * @param zzlxmc the value for T_ZHJC_YX_ZZLXTJ.ZZLXMC
     *
     * @mbggenerated
     */
    public void setZzlxmc(String zzlxmc) {
        this.zzlxmc = zzlxmc == null ? null : zzlxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.QHBM
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_ZZLXTJ.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.QHMC
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_ZZLXTJ.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.GXSJ
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_ZZLXTJ.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_ZZLXTJ.TJRQ
     *
     * @return the value of T_ZHJC_YX_ZZLXTJ.TJRQ
     *
     * @mbggenerated
     */
    public Date getTjrq() {
        return tjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_ZZLXTJ.TJRQ
     *
     * @param tjrq the value for T_ZHJC_YX_ZZLXTJ.TJRQ
     *
     * @mbggenerated
     */
    public void setTjrq(Date tjrq) {
        this.tjrq = tjrq;
    }
}