package com.css.cloud.quartz.zhjc.yxq.entity;

import java.util.Date;

public class TZhjcYxWbsd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.DRMSB
     *
     * @mbggenerated
     */
    private Short drmsb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.DRWSB
     *
     * @mbggenerated
     */
    private Short drwsb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.DRYCB
     *
     * @mbggenerated
     */
    private Short drycb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.QHBM
     *
     * @mbggenerated
     */
    private String qhbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.QHMC
     *
     * @mbggenerated
     */
    private String qhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.BMBM
     *
     * @mbggenerated
     */
    private String bmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.BMMC
     *
     * @mbggenerated
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZHJC_YX_WBSD.TJSJ
     *
     * @mbggenerated
     */
    private Date tjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.ID
     *
     * @return the value of T_ZHJC_YX_WBSD.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.ID
     *
     * @param id the value for T_ZHJC_YX_WBSD.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.DRMSB
     *
     * @return the value of T_ZHJC_YX_WBSD.DRMSB
     *
     * @mbggenerated
     */
    public Short getDrmsb() {
        return drmsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.DRMSB
     *
     * @param drmsb the value for T_ZHJC_YX_WBSD.DRMSB
     *
     * @mbggenerated
     */
    public void setDrmsb(Short drmsb) {
        this.drmsb = drmsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.DRWSB
     *
     * @return the value of T_ZHJC_YX_WBSD.DRWSB
     *
     * @mbggenerated
     */
    public Short getDrwsb() {
        return drwsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.DRWSB
     *
     * @param drwsb the value for T_ZHJC_YX_WBSD.DRWSB
     *
     * @mbggenerated
     */
    public void setDrwsb(Short drwsb) {
        this.drwsb = drwsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.DRYCB
     *
     * @return the value of T_ZHJC_YX_WBSD.DRYCB
     *
     * @mbggenerated
     */
    public Short getDrycb() {
        return drycb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.DRYCB
     *
     * @param drycb the value for T_ZHJC_YX_WBSD.DRYCB
     *
     * @mbggenerated
     */
    public void setDrycb(Short drycb) {
        this.drycb = drycb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.QHBM
     *
     * @return the value of T_ZHJC_YX_WBSD.QHBM
     *
     * @mbggenerated
     */
    public String getQhbm() {
        return qhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.QHBM
     *
     * @param qhbm the value for T_ZHJC_YX_WBSD.QHBM
     *
     * @mbggenerated
     */
    public void setQhbm(String qhbm) {
        this.qhbm = qhbm == null ? null : qhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.QHMC
     *
     * @return the value of T_ZHJC_YX_WBSD.QHMC
     *
     * @mbggenerated
     */
    public String getQhmc() {
        return qhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.QHMC
     *
     * @param qhmc the value for T_ZHJC_YX_WBSD.QHMC
     *
     * @mbggenerated
     */
    public void setQhmc(String qhmc) {
        this.qhmc = qhmc == null ? null : qhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.BMBM
     *
     * @return the value of T_ZHJC_YX_WBSD.BMBM
     *
     * @mbggenerated
     */
    public String getBmbm() {
        return bmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.BMBM
     *
     * @param bmbm the value for T_ZHJC_YX_WBSD.BMBM
     *
     * @mbggenerated
     */
    public void setBmbm(String bmbm) {
        this.bmbm = bmbm == null ? null : bmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.BMMC
     *
     * @return the value of T_ZHJC_YX_WBSD.BMMC
     *
     * @mbggenerated
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.BMMC
     *
     * @param bmmc the value for T_ZHJC_YX_WBSD.BMMC
     *
     * @mbggenerated
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.GXSJ
     *
     * @return the value of T_ZHJC_YX_WBSD.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.GXSJ
     *
     * @param gxsj the value for T_ZHJC_YX_WBSD.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZHJC_YX_WBSD.TJSJ
     *
     * @return the value of T_ZHJC_YX_WBSD.TJSJ
     *
     * @mbggenerated
     */
    public Date getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZHJC_YX_WBSD.TJSJ
     *
     * @param tjsj the value for T_ZHJC_YX_WBSD.TJSJ
     *
     * @mbggenerated
     */
    public void setTjsj(Date tjsj) {
        this.tjsj = tjsj;
    }
}